apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-kube
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu-server
      containers:
      - name: master
        image: qflow/jenkins-docker:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: var-run-docker-sock
        - mountPath: /var/jenkins_home
          name: data
      volumes:
      - name: var-run-docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: data
        hostPath:
          path: /data
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32597
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/add-base-url: /jenkins

spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          serviceName: jenkins-service
          servicePort: 80
        path: /jenkins
